/**
 * Format annotations into AI-friendly Markdown for the feedback file.
 *
 * The generated file is written to `.vibelens/feedback.md` in the project root
 * so any AI coding tool with filesystem access can read it.
 */

import type { Annotation } from '@vibelens/shared'

/** H14: AnnotationPayload uses the shared Annotation type */
export interface AnnotationPayload {
  pageUrl: string
  annotations: Annotation[]
}

const TYPE_LABELS: Record<string, string> = {
  comment: 'Comment',
  bug: 'Bug',
  suggestion: 'Suggestion',
  'style-change': 'Style Change',
}

const TYPE_EMOJI: Record<string, string> = {
  comment: '💬',
  bug: '🐛',
  suggestion: '💡',
  'style-change': '🎨',
}

/**
 * Format annotations into structured Markdown that AI tools can parse.
 */
export function formatFeedbackMarkdown(
  payload: AnnotationPayload,
  projectName: string,
): string {
  const { pageUrl, annotations } = payload

  // Only include unresolved annotations — resolved ones are "done"
  const active = annotations.filter((a) => !a.resolved)

  if (active.length === 0) {
    return [
      '# VibeLens Feedback',
      '',
      `> Project: **${projectName}**`,
      `> Page: ${pageUrl}`,
      `> Updated: ${new Date().toISOString()}`,
      '',
      '_No active annotations. All feedback has been resolved._',
      '',
    ].join('\n')
  }

  const lines: string[] = [
    '# VibeLens Feedback',
    '',
    `> Project: **${projectName}**`,
    `> Page: ${pageUrl}`,
    `> Updated: ${new Date().toISOString()}`,
    `> Active items: ${active.length}`,
    '',
    '---',
    '',
    '## Annotations',
    '',
  ]

  active.forEach((ann, i) => {
    const emoji = TYPE_EMOJI[ann.category] ?? '📝'
    const label = TYPE_LABELS[ann.category] ?? ann.category

    lines.push(`### ${i + 1}. ${emoji} ${label}`)
    lines.push('')
    lines.push(`**Message:** ${ann.message}`)
    lines.push('')
    lines.push(`**Element:** \`${ann.elementDescription}\``)
    lines.push('')
    lines.push(`**Selector:** \`${ann.selector}\``)
    lines.push('')

    // Include relevant computed styles for style-change annotations
    if (ann.category === 'style-change' && Object.keys(ann.computedStyles).length > 0) {
      lines.push('**Current styles:**')
      lines.push('```css')
      for (const [prop, value] of Object.entries(ann.computedStyles)) {
        lines.push(`  ${prop}: ${value};`)
      }
      lines.push('```')
      lines.push('')
    }

    lines.push('---')
    lines.push('')
  })

  lines.push(
    '_This file is auto-generated by VibeLens. ' +
    'Read it to understand what visual changes the user is requesting._',
  )
  lines.push('')

  return lines.join('\n')
}
