/**
 * H13+L2+L3: Inline style definitions for the VibeLens side panel.
 *
 * Extracted from App.tsx to reduce its line count. All styles are defined
 * as a single `S` record of CSS-in-JS objects, used by App.tsx and
 * its child components.
 */

export const S: Record<string, Record<string, string | number>> = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    background: '#0f0f0f',
    color: '#e0e0e0',
    overflow: 'hidden',
  },

  /* Header */
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    padding: '8px 10px 6px',
    borderBottom: '1px solid #1e1e1e',
    background: '#141414',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  brand: {
    fontWeight: 700,
    fontSize: '13px',
    letterSpacing: '-0.02em',
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    color: '#f0f0f0',
  },
  brandIcon: {
    fontSize: '14px',
    color: '#a78bfa',
  },
  iconBtn: {
    width: '26px',
    height: '26px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    border: '1px solid #2a2a2a',
    borderRadius: '5px',
    background: '#1a1a1a',
    color: '#999',
    cursor: 'pointer',
    lineHeight: 1,
  },
  statusDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    flexShrink: 0,
  },

  /* URL bar */
  urlRow: {
    display: 'flex',
    gap: '4px',
  },
  urlInput: {
    flex: 1,
    padding: '5px 8px',
    fontSize: '11px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
    border: '1px solid #2a2a2a',
    borderRadius: '5px',
    background: '#0a0a0a',
    color: '#d0d0d0',
    outline: 'none',
  },
  goBtn: {
    width: '30px',
    height: '28px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    fontWeight: 700,
    border: 'none',
    borderRadius: '5px',
    background: '#a78bfa',
    color: '#fff',
    cursor: 'pointer',
  },

  /* Viewport controls */
  viewportRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '2px',
  },
  viewportBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '3px',
    padding: '3px 6px',
    fontSize: '10px',
    border: '1px solid transparent',
    borderRadius: '4px',
    background: 'transparent',
    color: '#666',
    cursor: 'pointer',
  },
  viewportBtnActive: {
    borderColor: '#a78bfa44',
    background: '#a78bfa15',
    color: '#c4b5fd',
  },
  viewportIcon: {
    fontSize: '11px',
    lineHeight: 1,
  },
  viewportLabel: {
    fontSize: '10px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
  },
  viewportSize: {
    fontSize: '10px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
    color: '#444',
  },

  /* Preview area */
  previewContainer: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
    background: '#0a0a0a',
  },
  previewWrapper: {
    width: '100%',
    height: '100%',
    position: 'relative',
    overflow: 'hidden',
  },

  /* Empty state */
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    gap: '12px',
    padding: '24px',
    textAlign: 'center',
  },
  emptyIcon: {
    fontSize: '40px',
    color: '#a78bfa',
    opacity: 0.3,
  },
  emptyTitle: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#777',
  },
  emptyHint: {
    fontSize: '11px',
    color: '#555',
    lineHeight: 1.5,
  },
  codeSnippet: {
    padding: '1px 5px',
    fontSize: '10px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
    borderRadius: '3px',
    background: '#1a1a1a',
    color: '#a78bfa',
    border: '1px solid #2a2a2a',
  },
  emptySteps: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginTop: '8px',
    textAlign: 'left',
  },
  stepItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '11px',
    color: '#555',
  },
  stepNum: {
    width: '18px',
    height: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '9px',
    fontWeight: 700,
    borderRadius: '50%',
    background: '#1e1e1e',
    color: '#888',
    flexShrink: 0,
  },

  /* Annotation form overlay */
  formOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    background: 'rgba(0,0,0,0.6)',
    backdropFilter: 'blur(4px)',
    padding: '8px',
  },
  formCard: {
    background: '#1a1a1a',
    borderRadius: '8px',
    border: '1px solid #2a2a2a',
    padding: '10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  formHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  formTitle: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#e0e0e0',
  },
  formCloseBtn: {
    width: '20px',
    height: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    border: 'none',
    borderRadius: '4px',
    background: 'transparent',
    color: '#666',
    cursor: 'pointer',
  },
  formElement: {
    padding: '4px 6px',
    borderRadius: '4px',
    background: '#0f0f0f',
    border: '1px solid #222',
  },
  formElementCode: {
    fontSize: '10px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
    color: '#888',
    wordBreak: 'break-all',
  },
  formTypeRow: {
    display: 'flex',
    gap: '4px',
    flexWrap: 'wrap',
  },
  typeChip: {
    padding: '3px 8px',
    fontSize: '10px',
    border: '1px solid #333',
    borderRadius: '12px',
    background: '#111',
    color: '#888',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  formTextarea: {
    width: '100%',
    padding: '6px 8px',
    fontSize: '11px',
    fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif',
    border: '1px solid #2a2a2a',
    borderRadius: '5px',
    background: '#0a0a0a',
    color: '#d0d0d0',
    outline: 'none',
    resize: 'vertical',
    minHeight: '48px',
    boxSizing: 'border-box',
  },
  formActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '6px',
  },
  formCancelBtn: {
    padding: '4px 12px',
    fontSize: '11px',
    border: '1px solid #333',
    borderRadius: '5px',
    background: 'transparent',
    color: '#888',
    cursor: 'pointer',
  },
  formSaveBtn: {
    padding: '4px 14px',
    fontSize: '11px',
    fontWeight: 600,
    border: 'none',
    borderRadius: '5px',
    background: '#a78bfa',
    color: '#fff',
    cursor: 'pointer',
  },

  /* Annotation mode indicator */
  modeIndicator: {
    position: 'absolute',
    top: '8px',
    left: '50%',
    transform: 'translateX(-50%)',
    padding: '4px 12px',
    fontSize: '10px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
    borderRadius: '12px',
    background: '#a78bfa',
    color: '#fff',
    zIndex: 15,
    pointerEvents: 'none',
    whiteSpace: 'nowrap',
  },

  /* Reload toast */
  reloadToast: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    padding: '4px 10px',
    fontSize: '10px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
    borderRadius: '4px',
    background: '#a78bfa',
    color: '#fff',
    zIndex: 10,
    pointerEvents: 'none',
  },

  /* C1/C2: Write confirmation overlay */
  writeConfirmOverlay: {
    position: 'absolute',
    inset: '0',
    background: 'rgba(0, 0, 0, 0.6)',
    backdropFilter: 'blur(2px)',
    zIndex: 20,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
  },
  writeConfirmPanel: {
    background: '#1a1a2e',
    border: '1px solid #7c3aed',
    borderRadius: '8px',
    width: '100%',
    maxWidth: '360px',
    maxHeight: '70vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(124, 58, 237, 0.25)',
  },
  writeConfirmHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    padding: '10px 12px',
    borderBottom: '1px solid #2a2a4a',
    color: '#e0e0e0',
    fontSize: '12px',
  },
  writeConfirmDiff: {
    flex: '1',
    overflow: 'auto',
    margin: '0',
    padding: '10px 12px',
    fontSize: '10px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
    color: '#a0e0a0',
    background: '#0d0d1a',
    lineHeight: '1.5',
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
    maxHeight: '200px',
  },
  writeConfirmActions: {
    display: 'flex',
    gap: '8px',
    padding: '10px 12px',
    borderTop: '1px solid #2a2a4a',
    justifyContent: 'flex-end',
  },
  writeConfirmCancel: {
    padding: '5px 12px',
    border: '1px solid #555',
    borderRadius: '4px',
    background: 'transparent',
    color: '#aaa',
    fontSize: '11px',
    cursor: 'pointer',
  },
  writeConfirmApply: {
    padding: '5px 12px',
    border: 'none',
    borderRadius: '4px',
    background: '#7c3aed',
    color: '#fff',
    fontSize: '11px',
    fontWeight: '600',
    cursor: 'pointer',
  },

  /* Annotation drawer */
  drawer: {
    borderTop: '1px solid #1e1e1e',
    background: '#141414',
    maxHeight: '40vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  drawerToggle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '6px 10px',
    border: 'none',
    background: 'transparent',
    color: '#999',
    cursor: 'pointer',
    fontSize: '11px',
    textAlign: 'left',
  },
  drawerToggleText: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  resolvedCount: {
    color: '#555',
    fontSize: '10px',
  },
  drawerArrow: {
    fontSize: '8px',
    color: '#555',
  },
  drawerContent: {
    flex: 1,
    overflowY: 'auto',
    padding: '0 6px 6px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },

  /* Annotation list items */
  annotationItem: {
    padding: '6px 8px',
    borderRadius: '5px',
    background: '#1a1a1a',
    border: '1px solid #222',
    cursor: 'pointer',
    transition: 'border-color 0.15s ease',
  },
  annotationItemSelected: {
    borderColor: '#a78bfa',
  },
  annotationItemResolved: {
    opacity: 0.5,
  },
  annotationHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginBottom: '3px',
  },
  annotationIndex: {
    width: '18px',
    height: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '9px',
    fontWeight: 700,
    borderRadius: '50%',
    background: '#a78bfa',
    color: '#fff',
    flexShrink: 0,
  },
  annotationBadge: {
    padding: '1px 6px',
    fontSize: '9px',
    borderRadius: '8px',
    fontWeight: 500,
  },
  resolveBtn: {
    width: '18px',
    height: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '11px',
    border: 'none',
    borderRadius: '3px',
    background: 'transparent',
    color: '#555',
    cursor: 'pointer',
  },
  deleteBtn: {
    width: '18px',
    height: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    border: 'none',
    borderRadius: '3px',
    background: 'transparent',
    color: '#444',
    cursor: 'pointer',
  },
  annotationMessage: {
    fontSize: '11px',
    color: '#ccc',
    lineHeight: 1.4,
    marginBottom: '2px',
  },
  annotationSelector: {
    fontSize: '9px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
    color: '#555',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },

  /* Edit form (inline) */
  editForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginTop: '4px',
  },

  /* Push to IDE button */
  pushButton: {
    width: '100%',
    padding: '8px 12px',
    marginTop: '4px',
    border: 'none',
    borderRadius: '6px',
    background: '#a78bfa',
    color: '#fff',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'background 0.15s ease, opacity 0.15s ease',
  },
  pushButtonDone: {
    background: '#22c55e',
  },
  pushButtonDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
  },

  /* Status bar */
  statusBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px 10px',
    borderTop: '1px solid #1e1e1e',
    background: '#141414',
    fontSize: '10px',
    color: '#555',
  },
  statusDotSmall: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  statusLabel: {
    fontSize: '10px',
  },
  frameworkBadge: {
    padding: '1px 5px',
    fontSize: '9px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
    borderRadius: '3px',
    background: '#a78bfa22',
    color: '#a78bfa',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  viewportSizeSmall: {
    fontSize: '9px',
    fontFamily: 'SF Mono, Menlo, Consolas, monospace',
    color: '#444',
  },
}
